# Generated by Django 4.1.2 on 2022-10-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_menuitem_image_outlets_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemen',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.outlets'),
        ),
    ]
