# Generated by Django 4.1.2 on 2022-10-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_servicemen_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='servicemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.servicemen'),
        ),
    ]
