# Generated by Django 4.1.2 on 2022-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_menuitem_servicemen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
        migrations.AddField(
            model_name='servicemen',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
    ]
