# Generated by Django 4.1.2 on 2022-10-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_menuitem_location_servicemen_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemen',
            name='threshold',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
