# Generated by Django 4.1.2 on 2022-10-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_servicemen_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemen',
            name='service',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
