# Generated by Django 4.1.2 on 2022-10-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_servicemen_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemen',
            name='specialities',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
