# Generated by Django 4.1.2 on 2022-10-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemen',
            name='price',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
