# Generated by Django 4.1.2 on 2022-10-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.outlets'),
        ),
    ]
